name: 构建NDK库
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip source
        run: unzip jni.src.zip -d .
      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: 25.2.9519653
      - name: Find and build
        run: |
          # 自动找到包含 Android.mk 的目录并构建
          ANDROID_MK_DIR=$(find . -name "Android.mk" -exec dirname {} \;)
          ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/25.2.9519653
          cd "$ANDROID_MK_DIR"
          $ANDROID_NDK_ROOT/ndk-build
      - name: Upload built libs
        uses: actions/upload-artifact@v4
        with:
          name: built-libs
          path: "**/libs/"
